# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  cpython:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m nose2 -B  tests

      - name: Run flake8
        run: |
          python -m flake8 --exit-zero

      - name: Run vulture
        run: |
          python -m vulture dataclass_factory --min-confidence 70

      - name: Run Mypy
        run: |
          python -m mypy --pretty dataclass_factory tests

  pypy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        pypy-version: ['pypy3']

    steps:
      - uses: actions/checkout@v2
      - name: Install Pypy
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pypy-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements_pypy.txt

      - name: Run tests
        run: |
          nose2 -B -C tests

